// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1WqbCKMn8ZcddoBehAx3VRvM32ue4V1g',
    appId: '1:407543820773:web:e124615f114d2cb89bff0c',
    messagingSenderId: '407543820773',
    projectId: 'techathon-d31c3',
    authDomain: 'techathon-d31c3.firebaseapp.com',
    databaseURL: 'https://techathon-d31c3-default-rtdb.firebaseio.com',
    storageBucket: 'techathon-d31c3.firebasestorage.app',
    measurementId: 'G-B3SN8GWXP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_7ixkLNv5OdW54-YE21dhLRtbJELz6HY',
    appId: '1:407543820773:android:dffb74690c8717d29bff0c',
    messagingSenderId: '407543820773',
    projectId: 'techathon-d31c3',
    databaseURL: 'https://techathon-d31c3-default-rtdb.firebaseio.com',
    storageBucket: 'techathon-d31c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5DmtQj3YAL_zPjXUQj2VZRIpcig7aNC8',
    appId: '1:407543820773:ios:099d6489bdfbba1a9bff0c',
    messagingSenderId: '407543820773',
    projectId: 'techathon-d31c3',
    databaseURL: 'https://techathon-d31c3-default-rtdb.firebaseio.com',
    storageBucket: 'techathon-d31c3.firebasestorage.app',
    androidClientId: '407543820773-cit13c9psnnakpoha92jimsqkalqqspb.apps.googleusercontent.com',
    iosClientId: '407543820773-4arne82kahgrq22rd33icl6aj8e14pof.apps.googleusercontent.com',
    iosBundleId: 'com.example.cns',
  );
}
